'use strict';

const fs         = require('fs');
const path       = require('path');
const { exec }   = require('child_process');
const logger     = require('../utils/logger');
const config     = require('../config/env');

/**
 * RenderService — Milestone 4
 *
 * Merges gameplay footage + narration audio + SRT captions into a final MP4.
 *
 * G1.mp4 is already 1080x1920 @ 30fps — no scaling needed.
 *
 * WHY exec (shell) instead of execFile (no-shell):
 *   FFmpeg 8.x has strict single-quote nesting inside its filter graph parser.
 *   When -vf contains both 'path' and force_style='...', passing via execFile[]
 *   causes quote boundary confusion inside FFmpeg itself.
 *   Using exec() lets the OS shell double-quote the whole -vf value,
 *   so FFmpeg receives a clean, unambiguous filter string.
 *   All paths are generated by us (timestamps only), never raw user input.
 */
class RenderService {
  /**
   * Render the final video.
   *
   * @param {Object} input
   * @param {string} input.gameplayPath     - Path to gameplay .mp4
   * @param {number} input.startSeconds     - Where in gameplay to start
   * @param {string} input.audioPath        - Path to narration .mp3
   * @param {string} input.srtPath          - Path to captions .srt
   * @param {string} input.outputPath       - Where to write final .mp4
   * @param {number} input.durationSeconds  - Target video duration
   * @param {Object} [input.options]
   * @param {string} [input.options.crf]      - CRF quality 0-51 (default '23')
   * @param {string} [input.options.preset]   - FFmpeg preset (default 'fast')
   * @param {string} [input.options.fontName] - Subtitle font (default 'Impact')
   * @param {number} [input.options.fontSize] - Subtitle font size (default 18)
   */
  async render(input) {
    const {
      gameplayPath,
      startSeconds,
      audioPath,
      srtPath,
      outputPath,
      durationSeconds,
      options = {},
    } = input;

    // ── Validate inputs ──────────────────────────────────────────────────
    this._assertFileExists(gameplayPath, 'gameplayPath');
    this._assertFileExists(audioPath,    'audioPath');
    this._assertFileExists(srtPath,      'srtPath');

    if (!outputPath)    throw new Error('[RenderService] outputPath is required');
    if (!durationSeconds || durationSeconds <= 0) {
      throw new Error('[RenderService] durationSeconds must be a positive number');
    }

    const ffmpegBin = this._resolveFFmpeg();
    const preset    = options.preset   || 'fast';
    const crf       = options.crf      || '23';
    const fontName  = options.fontName || 'Impact';
    const fontSize  = options.fontSize || 18;

    const step = logger.step('video_render', {
      gameplayPath: path.basename(gameplayPath),
      startSeconds,
      durationSeconds,
      audioPath:    path.basename(audioPath),
      srtPath:      path.basename(srtPath),
      outputPath,
    });

    try {
      fs.mkdirSync(path.dirname(outputPath), { recursive: true });

      // ── SRT path: escape colons for FFmpeg filter syntax ─────────────────
      const srtForFilter = srtPath.replace(/\\/g, '/').replace(/:/g, '\\:');

      // ── Check if subtitles filter is available in this FFmpeg build ───────
      // The standard Homebrew ffmpeg is compiled without libass (no subtitles filter).
      // If not available, render without captions (pipeline still proves itself).
      // Install ffmpeg-full for full caption support.
      const hasSubtitles = await this._hasSubtitlesFilter(ffmpegBin);
      const isASS        = srtPath.toLowerCase().endsWith('.ass');

      let vfArg = '';
      if (hasSubtitles) {
        if (isASS) {
          // ASS files carry all styling in their header — just point the filter at the file.
          // Using `ass` filter (not `subtitles`) for full ASS feature support (animations, transforms).
          vfArg = `-vf "ass='${srtForFilter}'"`;
          logger.info('[RenderService] ASS subtitle burn-in enabled', { srtForFilter });
        } else {
          // SRT fallback with force_style overrides
          const forceStyle = [
            `FontName=${fontName}`,
            `FontSize=${fontSize}`,
            `PrimaryColour=&H00FFFFFF`,
            `OutlineColour=&H00000000`,
            `BackColour=&H80000000`,
            `Outline=2`,
            `Shadow=1`,
            `Bold=1`,
            `Alignment=2`,
            `MarginV=120`,
          ].join(',');
          const vfFilter = `subtitles='${srtForFilter}':force_style='${forceStyle}'`;
          vfArg = `-vf "${vfFilter}"`;
          logger.info('[RenderService] SRT subtitle burn-in enabled', { srtForFilter });
        }
      } else {
        logger.warn('[RenderService] subtitles/ass filter not available. Rendering without captions. Run: brew install ffmpeg-full');
      }

      // ── BGM: look for G2.mp3 in footage dir or project root ─────────────
      const footageDir = path.dirname(gameplayPath);
      const bgmCandidates = [
        path.join(footageDir, 'G2.mp3'),
        path.resolve('./G2.mp3'),
        path.resolve('./footage/gameplay/G2.mp3'),
      ];
      const bgmPath = bgmCandidates.find(p => fs.existsSync(p)) || null;
      const hasBGM  = bgmPath !== null;

      if (hasBGM) {
        logger.info('[RenderService] BGM found, will mix at low volume', { bgmPath });
      }

      // ── Build FFmpeg command ──────────────────────────────────────────────
      // When BGM is present we add it as a 3rd input and use amix to blend
      // narration (full volume) + BGM (low-medium ~15%) into one audio stream.
      const shellCmd = [
        `"${ffmpegBin}"`,
        `-ss ${startSeconds}`,
        `-t ${durationSeconds + 1}`,
        `-i "${gameplayPath}"`,          // input 0: gameplay video
        `-i "${audioPath}"`,             // input 1: narration
        hasBGM ? `-stream_loop -1 -i "${bgmPath}"` : '', // input 2: BGM (looped)
        vfArg,                           // subtitle filter (empty when unavailable)
        `-c:v libx264`,
        `-preset ${preset}`,
        `-crf ${crf}`,
        hasBGM
          ? `-filter_complex "[1:a]volume=1.8[narr];[2:a]volume=0.40,atrim=0:${durationSeconds + 1}[bgm];[narr][bgm]amix=inputs=2:duration=shortest:dropout_transition=2[aout]" -map 0:v:0 -map "[aout]"`
          : `-filter_complex "[1:a]volume=1.8[aout]" -map 0:v:0 -map "[aout]"`,
        `-c:a aac`,
        `-b:a 128k`,
        `-shortest`,
        `-movflags +faststart`,
        `-y`,
        `"${outputPath}"`,
      ].filter(Boolean).join(' ');    // filter(Boolean) removes empty vfArg

      logger.debug('[RenderService] Shell command', { shellCmd });

      const renderStart    = Date.now();
      await this._execShell(shellCmd);
      const render_time_ms = Date.now() - renderStart;

      const stats           = fs.statSync(outputPath);
      const file_size_bytes = stats.size;

      const result = {
        outputPath,
        durationSeconds,
        file_size_bytes,
        file_size_mb:   parseFloat((file_size_bytes / 1024 / 1024).toFixed(2)),
        render_time_ms,
        render_time_s:  parseFloat((render_time_ms / 1000).toFixed(1)),
        ffmpegCommand:  shellCmd,
      };

      step.done({
        file_size_mb:  result.file_size_mb,
        render_time_s: result.render_time_s,
        outputPath,
      });

      return result;

    } catch (err) {
      step.fail(err);
      throw err;
    }
  }

  // ── Private ─────────────────────────────────────────────────────────────

  _resolveFFmpeg() {
    const candidates = [
      config.ffmpeg.path,
      '/opt/homebrew/bin/ffmpeg',
      '/usr/local/bin/ffmpeg',
    ].filter(Boolean);

    for (const c of candidates) {
      if (fs.existsSync(c)) return c;
    }
    return 'ffmpeg';
  }

  /** Returns true if this FFmpeg binary has the subtitles filter (requires libass). */
  _hasSubtitlesFilter(ffmpegBin) {
    return new Promise((resolve) => {
      exec(`"${ffmpegBin}" -filters 2>&1 | grep -c subtitles`, (err, stdout) => {
        const count = parseInt((stdout || '0').trim(), 10);
        resolve(count > 0);
      });
    });
  }

  _assertFileExists(filePath, label) {
    if (!filePath) throw new Error(`[RenderService] ${label} is required`);
    if (!fs.existsSync(path.resolve(filePath))) {
      throw new Error(`[RenderService] ${label} not found: ${path.resolve(filePath)}`);
    }
  }

  _execShell(cmd) {
    return new Promise((resolve, reject) => {
      const proc = exec(cmd, { maxBuffer: 100 * 1024 * 1024 }, (err, stdout, stderr) => {
        if (err) {
          const lastLines = (stderr || '')
            .split('\n')
            .filter(Boolean)
            .slice(-15)
            .join('\n');
          return reject(
            new Error(`[RenderService] FFmpeg failed (exit ${err.code}):\n${lastLines}`)
          );
        }
        resolve({ stdout, stderr });
      });

      proc.stderr?.on('data', (chunk) => {
        const line = chunk.toString().trim();
        if (line.includes('frame=') || line.includes('time=') || line.includes('speed=')) {
          logger.debug('[FFmpeg]', { progress: line });
        }
      });
    });
  }
}

module.exports = new RenderService();
